- flags:
  - default: false
- functions:
  - { name: error, within: [] }
  - { name: undefined, within: [] }
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
- ignore: { name: Use tuple-section }
